### ISSUE TITLE
Can't get this working with Electron Builder

### ISSUE THREAD

**Issue by oblomki** [mceachen/exiftool-vendored.js#19] opened 2018-04-02 14:10 UTC
Hello there @mceachen,

Excellent package, thanks a lot. I need to get this working with a multi-platform Electron Builder build, and am having no luck so far.

You mentioned in a previous issue that you had managed to get this working using a few tricks:

> It took me a while to get the right combination of electron packaging (I am using electron-builder ), webpack config, asar exclusions, and __dirname workarounds to make everything work cross-platform.

Would you mind sharing exactly what you did?

Thanks again.

**Comment by mceachen** [comment] 2018-04-02 15:28
The electron integration code I've written is not open source, sorry. I added to https://github.com/mceachen/exiftool-vendored.js/wiki#how-do-you-make-this-work-with-electron. Closed as dupe of #17.

**Closed by mceachen** 2018-04-02 15:28 UTC
